#!/bin/bash
set -e

# 설정 변수
KEY_MANAGER_HOST="192.168.0.230"
REGISTRATION_TOKEN="U22sK5xJoyEDRuLpCijA7sq8BAMUVXvVlMsUBWoaWa1zEO1n4OWStqnqtPHdDGZz"
HOST_PORT_CRDP=32682
HOST_PORT_HEALTHZ=32680

docker run -d -e KEY_MANAGER_HOST=$KEY_MANAGER_HOST -e REGISTRATION_TOKEN=$REGISTRATION_TOKEN \
  --restart unless-stopped -p $HOST_PORT_CRDP:8090 -p $HOST_PORT_HEALTHZ:8080 -e SERVER_MODE=no-tls \
  thalesciphertrust/ciphertrust-restful-data-protection
